# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b125267b3ba469b4e0d4251597f4f934d39fa9342a4f8f487debe121d37f826243839184ef53daab39fcab3b111e3d283cae368a2778a570d73a81291f3bc713

test:
  secret_key_base: 19a5afdbeb6929780a316f8b3b73f6bd6e18e72c78d6d25f6c16ce0530a84f48a1e11563f47800cfd739bd5f7b1be6fb8a5d18c29f797235b2b35ac32886fa32

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
